### ISSUE TITLE
disabling it in Firecrap, err Firefox, doesn't seem to work

### ISSUE THREAD

**Issue by calestyo** [stevespringett/disable-webassembly#1]
Even when the respective about:config option is set to false, the example at http://webassembly.org/demo/ runs "normal".

**Comment by stevespringett** [comment]
I cannot replicate. Using FireFox 58.0, these are the results I'm seeings with the setting enabled and disabled.

<img width="1238" alt="wasm-enabled" src="https://user-images.githubusercontent.com/3878933/35486332-61972c24-0432-11e8-9380-83f8d6d360b2.png">

<img width="1238" alt="wasm-disabled" src="https://user-images.githubusercontent.com/3878933/35486334-656ce58c-0432-11e8-9d84-1f8628e29528.png">

I noticed the demo had a fallback option. I tried disabling javascript.options.asmjs, but that did not work for me. The demo continued to work.

**Comment by calestyo** [comment]
I think you're right... I must have gotten into the fallback demo and haven't noticed this.

**Comment by ghost** [comment]
On FF, you also need: <code>javascript.options.<strong>asmjs</strong></code> -&gt; <code>false</code>.

<table><tr><td>
When <del>Firefox</del> <em>Firecrap</em><sup>⇙︎ ha! </sup> meets a WebAssembly code, <br/>
it first tries to translate it to native-instructions,<br/>
and then it runs it through the <code>wasm</code>-engine, for speed,<br/>
but if translating is not possible, or the <code>wasm</code>-engine isn't available, <br/>
FF <em>can still run the code</em> plainly, as a non-optimized JavaScript-code.

...so disable both <code>wasm</code> and <code>asmjs</code>
</td></tr></table>


https://hg.mozilla.org/releases/mozilla-release/file/tip/modules/libpref/init/all.js#l1338
https://hg.mozilla.org/releases/mozilla-release/file/02a265554b08/js/xpconnect/src/XPCJSContext.cpp#l686

**Comment by calestyo** [comment]
@eladkarako But AFAIU asmjs is just a subset of JS, isn't it? So if that would be true, than any harm that asmjs could to could already be done by plain JS and as such, disabling asmjs should only improve security, if one also disables JS itself completely,...

Right?
